[package]
name = "wasm-image-decoder"
version = "0.0.5"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-rayon = {version = "1.0.3", features = ["no-bundler"]}
console_error_panic_hook = "0.1.6"
image = "0.24.0"
